language: bash

# cache:
#   directories:
#     - /home/travis/docker/

# env:
#   global:
#     - OPENRESTY_IMAGE=/home/travis/docker/openresty_image.tar.gz

services:
  - docker

before_install:
  - make pull_image

script:
  - make
