app:
        image: "nickxiao/openresty-testsuite:latest"
        command: "sh"
        container_name: "lua-resty-console-tests"
        volumes:
                - ".:/lua-resty-console"
        working_dir: "/lua-resty-console"


